services:
  wii-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wii-dev-container
    #user: "1000:1000"
    volumes:
      - ../:/workspace:Z
    working_dir: /workspace
    stdin_open: true
    tty: true
    # Podman-specific runtime config
    tmpfs:
      - /run
    environment:
      - HOME=/home/dev